export interface ContrastColor {
    [key: string]: string;
  }

export const DefaultColors: ContrastColor = {
    'bs-body-bg': '#fff',
    'bs-card-bg': '#fff',
    'bs-card-title-color-title': '',
    'bs-badge-color-badge': '#fff',
    'bs-primary-rgb': '13, 110, 253',
    'bs-navbar-color-navbar': 'rgba(255, 255, 255, 0.55)',
    'bs-light-rgb': '248, 249, 250',
    'bs-navbar-hover-color-navbar': 'rgba(255, 255, 255, 0.75)',
    'bs-navbar-brand-color-navbar': 'rgba(0, 0, 0, 0.9)',
    'navbar-brand-color': 'white',
    'bs-white-rgb': '255, 255, 255',
    'text-muted-text': '#6c757d',
    'bs-accordion-active-background': '#e7f1ff',
    'bs-accordion-active-color-active': '#0c63e4',
    'bs-accordion-background': '#fff',
    'bs-accordion-btn-color-btn': '#212529',
    'bs-primary-rgb2': '92, 184, 92',
    'bs-btn-color-btn-contrast': '#fff',
    'bs-btn-background': '#0d6efd',
    'card-body-background': 'white',
    'bs-link-color': '#0d6efd',
    'bs-link-hover-color': '#0a58ca',
    'bs-btn-hover-background': '#f8f9fa',
    'bs-btn-hover-color-hover': 'black',
    'bs-btn-hover-background-primary': '#0a58ca',
    '-bs-btn-hover-color-primary': 'white',
    
};

export const ContrastColors: ContrastColor = {
    'bs-body-bg': '#000',
    'bs-card-background': '#3d3d3d',
    'bs-card-title-color-title': 'yellow',
    'bs-badge-color-badge': 'yellow',
    'bs-primary-rgb': '0, 0, 0',
    'bs-navbar-color-navbar': 'yellow',
    'bs-light-rgb': '0, 0, 0',
    'bs-navbar-hover-color-navbar': 'rgba(179, 179, 84, 0.75)',
    'bs-navbar-brand-color-navbar': 'yellow',
    'navbar-brand-color': 'yellow',
    'bs-white-rgb': 'yellow',
    'text-muted-text': 'yellow',
    'bs-accordion-active-background': '#3d3d3d',
    'bs-accordion-active-color-active': 'yellow',
    'bs-accordion-background': 'black',
    'bs-accordion-btn-color-btn': 'white',
    'bs-primary-rgb2': '255, 255, 0',
    'bs-btn-color-btn-contrast': 'yellow',
    'bs-btn-background': 'black',
    'card-body-background': '#3d3d3d',
    'bs-link-color': 'white',
    'bs-link-hover-color': 'rgba(179, 179, 84, 0.75)',
    'bs-btn-hover-background': '#3d3d3d',
    'bs-btn-hover-color-hover': 'yellow',
    'bs-btn-hover-background-primary': 'dark-grey',
    'bs-btn-hover-color-primary': 'yellow',
};